apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/MparrillaL/cei-test-manu'
    path: cei-test-manu/apps

    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: rollout-demo
  syncPolicy:
    automated: {}
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
